spring:
  application:
    name: patient-import-service

  datasource:
    url: jdbc:postgresql://localhost:5432/labdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  batch:
    job:
      enabled: false  # Prevent auto-start of jobs
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.lab: DEBUG
    org.springframework.batch: INFO